/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author hp-ori
 */
public class Calculadora extends javax.swing.JFrame {
//        inicia la clase calculadora e importa la libreria javaSwing

    private String cadenaNumeros = "";
    private String operacion = "nula";
    private Double primerNumero;
    private Double resultado;
    private boolean activado = true;
    private boolean punto = true;

    public Calculadora() {
        initComponents();

        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
//        metodo que inicializa los componentes (Constructor)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDiv = new javax.swing.JButton();
        botonCE = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonMulti = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        botonDif = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        etiquetaNumeros = new javax.swing.JLabel();
        etiquetaMuestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridLayout(5, 4));

        botonC.setBackground(new java.awt.Color(255, 255, 153));
        botonC.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        panel.add(botonC);

        botonRaiz.setBackground(new java.awt.Color(204, 255, 204));
        botonRaiz.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonRaiz.setText("√");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        panel.add(botonRaiz);

        botonDiv.setBackground(new java.awt.Color(204, 255, 204));
        botonDiv.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonDiv.setText("/");
        botonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivActionPerformed(evt);
            }
        });
        panel.add(botonDiv);

        botonCE.setBackground(new java.awt.Color(255, 255, 153));
        botonCE.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonCE.setText("CE");
        botonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCEActionPerformed(evt);
            }
        });
        panel.add(botonCE);

        botonSiete.setBackground(new java.awt.Color(255, 255, 204));
        botonSiete.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonSiete.setText("7");
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });
        panel.add(botonSiete);

        botonOcho.setBackground(new java.awt.Color(255, 255, 204));
        botonOcho.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonOcho.setText("8");
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });
        panel.add(botonOcho);

        botonNueve.setBackground(new java.awt.Color(255, 255, 204));
        botonNueve.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonNueve.setText("9");
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });
        panel.add(botonNueve);

        botonMulti.setBackground(new java.awt.Color(204, 255, 204));
        botonMulti.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonMulti.setText("x");
        botonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiActionPerformed(evt);
            }
        });
        panel.add(botonMulti);

        botonCuatro.setBackground(new java.awt.Color(255, 255, 204));
        botonCuatro.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonCuatro.setText("4");
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });
        panel.add(botonCuatro);

        botonCinco.setBackground(new java.awt.Color(255, 255, 204));
        botonCinco.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonCinco.setText("5");
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });
        panel.add(botonCinco);

        botonSeis.setBackground(new java.awt.Color(255, 255, 204));
        botonSeis.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonSeis.setText("6");
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });
        panel.add(botonSeis);

        botonMenos.setBackground(new java.awt.Color(204, 255, 204));
        botonMenos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonMenos.setText("-");
        botonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosActionPerformed(evt);
            }
        });
        panel.add(botonMenos);

        botonUno.setBackground(new java.awt.Color(255, 255, 204));
        botonUno.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonUno.setText("1");
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });
        panel.add(botonUno);

        botonDos.setBackground(new java.awt.Color(255, 255, 204));
        botonDos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonDos.setText("2");
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });
        panel.add(botonDos);

        botonTres.setBackground(new java.awt.Color(255, 255, 204));
        botonTres.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonTres.setText("3");
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTresActionPerformed(evt);
            }
        });
        panel.add(botonTres);

        botonMas.setBackground(new java.awt.Color(204, 255, 204));
        botonMas.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonMas.setText("+");
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasActionPerformed(evt);
            }
        });
        panel.add(botonMas);

        botonDif.setBackground(new java.awt.Color(204, 255, 204));
        botonDif.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonDif.setText("+/-");
        botonDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDifActionPerformed(evt);
            }
        });
        panel.add(botonDif);

        botonCero.setBackground(new java.awt.Color(204, 255, 204));
        botonCero.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });
        panel.add(botonCero);

        botonPunto.setBackground(new java.awt.Color(204, 255, 204));
        botonPunto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        panel.add(botonPunto);

        botonIgual.setBackground(new java.awt.Color(204, 255, 204));
        botonIgual.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        panel.add(botonIgual);

        etiquetaNumeros.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        etiquetaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNumeros.setText("0");

        etiquetaMuestra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaMuestra.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(etiquetaMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    en los siguientes eventos se hara la accion la cual si presionamos un numero en la vista, que esto se vea reflejado en el ´panel
//        asi para cada numero de nuestra calculadora
    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed

//        aqui reconoce si etiqueta numeros contiene algo en el panel
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "7";
        } else {
            cadenaNumeros += "7";
        }
        etiquetaNumeros.setText(cadenaNumeros);
//        para que me muestre lo presionado le mando el valor de la cadena
//        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
//          variable que me va a permitir seguir usando la calculadora
    }//GEN-LAST:event_botonSieteActionPerformed

    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "8";
        } else {
            cadenaNumeros += "8";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonOchoActionPerformed

    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        // TODO add your handling code here: 
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "9";
        } else {
            cadenaNumeros += "9";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "4";
        } else {
            cadenaNumeros += "4";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonCuatroActionPerformed

    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "5";
        } else {
            cadenaNumeros += "5";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonCincoActionPerformed

    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "6";
        } else {
            cadenaNumeros += "6";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonSeisActionPerformed

    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "1";
        } else {
            cadenaNumeros += "1";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonUnoActionPerformed

    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "2";
        } else {
            cadenaNumeros += "2";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonDosActionPerformed

    private void botonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTresActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "3";
        } else {
            cadenaNumeros += "3";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonTresActionPerformed

    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
        // TODO add your handling code here:
        if (etiquetaNumeros.getText().equals("0")) {
            cadenaNumeros = "0";
        } else {
            cadenaNumeros += "0";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonCeroActionPerformed

    private void botonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasActionPerformed
        // TODO add your handling code here:
//        aqui con la variable activado sabemos si se ha ingresado un valor en la calcu
        if (activado = true) {
//            como se ha ingresado un valor entonces procedemos a mostrar la informacion en el panel superior
            primerNumero = Double.parseDouble(cadenaNumeros);
//            se hace un parseo para trabajar en numeros double
            etiquetaMuestra.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
//            se resetea la cadena para ingresar el otro operando
            operacion = "sumar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonMasActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        double segundoNumero;
//           creamos la variable que contendra el segundo operando
//en estos metodos se hacen las operaciones respectivas de acuerdo a la entrada del evento suma, resta, div etc
        if (operacion.equals("nula")) {
            etiquetaNumeros.setText(cadenaNumeros);
        } else if (operacion.equals("sumar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;
            etiquetaNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        } else if (operacion.equals("restar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;
            etiquetaNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        } else if (operacion.equals("multiplicar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;
            etiquetaNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        } else if (operacion.equals("div")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            if (segundoNumero == 0) {
                etiquetaNumeros.setText("∞");
            } else {
                resultado = primerNumero / segundoNumero;
                etiquetaNumeros.setText(String.format("% .2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            }
        }
        etiquetaMuestra.setText("");
        activado = true;
        punto = false;
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiActionPerformed
        // TODO add your handling code here:
        if (activado = true) {
//            como se ha ingresado un valor entonces procedemos a mostrar la informacion en el panel superior
            primerNumero = Double.parseDouble(cadenaNumeros);
//            se hace un parseo para trabajar en numeros double
            etiquetaMuestra.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
//            se resetea la cadena para ingresar el otro operando
            operacion = "multiplicar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonMultiActionPerformed

    private void botonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosActionPerformed
        // TODO add your handling code here:
        if (activado = true) {
//            como se ha ingresado un valor entonces procedemos a mostrar la informacion en el panel superior
            primerNumero = Double.parseDouble(cadenaNumeros);
//            se hace un parseo para trabajar en numeros double
            etiquetaMuestra.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
//            se resetea la cadena para ingresar el otro operando
            operacion = "restar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonMenosActionPerformed

    private void botonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivActionPerformed
        if (activado = true) {
//            como se ha ingresado un valor entonces procedemos a mostrar la informacion en el panel superior
            primerNumero = Double.parseDouble(cadenaNumeros);
//            se hace un parseo para trabajar en numeros double
            etiquetaMuestra.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
//            se resetea la cadena para ingresar el otro operando
            operacion = "div";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonDivActionPerformed

    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        // TODO add your handling code here:
        primerNumero = Double.parseDouble(cadenaNumeros);
        etiquetaMuestra.setText("sqr(" + cadenaNumeros + ")");
        resultado = Math.sqrt(primerNumero);
        etiquetaNumeros.setText(String.format("% .2f", resultado));
        cadenaNumeros = String.valueOf(resultado); //convertimos el valor a cadena
        activado = false;
        punto = false;
    }//GEN-LAST:event_botonRaizActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if (punto == true) {
            if (cadenaNumeros.equals("")) {
//                si el panel esta vacio, si no se ha ingresado nada entonces agrega 0.
                cadenaNumeros = "0. ";
            } else {
//                si ya existe un numero en el panel etonces solo agrega el punto
                cadenaNumeros += ".";
            }
            etiquetaNumeros.setText(cadenaNumeros);
            punto = false;
//                una vez ya agregado el punto en  el numero esto no me permitira agregar otra vez el punto
        }
        punto = false;
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDifActionPerformed
        // TODO add your handling code here:
        if (cadenaNumeros.charAt(0) != '-') {
//            compara si la cadena tiene un - (valor negativo), si es falso agrega el "-" a la cadena para hacer el numero negativo
            cadenaNumeros = "-" + cadenaNumeros;
        } else {
            //si no se cumple quiere decir que el valor es negativo y se agrega un mas 
            cadenaNumeros = cadenaNumeros.substring(1, cadenaNumeros.length());
        }
        etiquetaNumeros.setText(cadenaNumeros);
    }//GEN-LAST:event_botonDifActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
//        en este apartado reseteamos todas nuestras variables
        etiquetaMuestra.setText("");
        etiquetaNumeros.setText("0");
        cadenaNumeros = "";
        operacion = "nula";
        activado = true;
        punto = true;
    }//GEN-LAST:event_botonCActionPerformed

    private void botonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCEActionPerformed
        // TODO add your handling code here:
//        este metodo va a ir recortando los valores finales del operador ingresado
        int tamaño = cadenaNumeros.length();
//        con esta variablñe calculamos la longitud
        if (tamaño == 1) {
            cadenaNumeros = "0";
        } else {
            cadenaNumeros = cadenaNumeros.substring(0, cadenaNumeros.length() - 1);
//             aqui le vamos quitando a partir de la posicion
        }
        etiquetaNumeros.setText(cadenaNumeros);
//        aqui vamos mostrando lo recortado
    }//GEN-LAST:event_botonCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
//        metodo principal
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* IbotonC (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        agregamos la libreria Jtatooo y con esta instruccion agregamos un tema al form
        UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
//            Este metodo hace visible o no el formulario a partir de la funcion .setVisible
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonCE;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDif;
    private javax.swing.JButton botonDiv;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonMulti;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetaNumeros;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
